[package]
name = "sourcemap"
version = "3.0.1"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["javascript", "sourcemap", "sourcemaps"]
description = "Basic sourcemap handling for Rust"
homepage = "https://github.com/mitsuhiko/rust-sourcemap"
documentation = "http://mitsuhiko.github.io/rust-sourcemap/"
license = "BSD-3-Clause"
readme = "README.md"
build = "build.rs"
edition = "2018"

[dependencies]
url = "1.7.2"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.38"
base64 = "0.10.1"
regex = "1.1.0"
lazy_static = "1.2.0"
if_chain = "0.1.3"

[build-dependencies]
rustc_version = "0.2.3"
